### ISSUE TITLE
How do you generate `.d.ts` files?

### ISSUE THREAD

**Issue by Industrial** [Banou26/parcel-plugin-babel-typescript#3]
Hi.

Using this plugin I get no `.d.ts` files compiled. If I run `tsc` instead then it will compile those files. I have the correct options set in the `tsconf.json`.

gr,

Tom

**Comment by Banou26** [comment]
Hey,

This problem isn't in the scope of this plugin, all this plugin does is use babel's typescript transform instead of tsc itself.

As https://github.com/babel/babel/issues/9668#issuecomment-496028696 describes it, babel typescript plugin's goal isn't to make babel understand typescript, only its syntax.

So you'll still have to use tsc for the actual generation of these definition files.

To come back to your problem, you could transpile your project using babel with `@babel/plugin-syntax-typescript` and whitout `@babel/preset-typescript`/`@babel/plugin-transform-typescript` to keep all of the types but transpile your proposals, and then use tsc on the output.

I'm closing the issue since it's not in the scope of this plugin.
